language: node_js
script: 'npm run build && npm start'
node_js:
  - '10'
cache: npm
env:
 - PAGE=900
 - PAGE=901
 - PAGE=902
 - PAGE=903
 - PAGE=904
 - PAGE=905
 - PAGE=906
 - PAGE=907
 - PAGE=908
 - PAGE=909
 - PAGE=910
 - PAGE=911
 - PAGE=912
 - PAGE=913
 - PAGE=914
 - PAGE=915
 - PAGE=916
 - PAGE=917
 - PAGE=918
 - PAGE=919
 - PAGE=920
 - PAGE=921
 - PAGE=922
 - PAGE=923
 - PAGE=924
 - PAGE=925
 - PAGE=926
 - PAGE=927
 - PAGE=928
 - PAGE=929
 - PAGE=930
 - PAGE=931
 - PAGE=932
 - PAGE=933
 - PAGE=934
 - PAGE=935
 - PAGE=936
 - PAGE=937
 - PAGE=938
 - PAGE=939
 - PAGE=940
 - PAGE=941
 - PAGE=942
 - PAGE=943
 - PAGE=944
 - PAGE=945
 - PAGE=946
 - PAGE=947
 - PAGE=948
 - PAGE=949
 - PAGE=950
 - PAGE=951
 - PAGE=952
 - PAGE=953
 - PAGE=954
 - PAGE=955
 - PAGE=956
 - PAGE=957
 - PAGE=958
 - PAGE=959
 - PAGE=960
 - PAGE=961
 - PAGE=962
 - PAGE=963
 - PAGE=964
 - PAGE=965
 - PAGE=966
 - PAGE=967
 - PAGE=968
 - PAGE=969
 - PAGE=970
 - PAGE=971
 - PAGE=972
 - PAGE=973
 - PAGE=974
 - PAGE=975
 - PAGE=976
 - PAGE=977
 - PAGE=978
 - PAGE=979
 - PAGE=980
 - PAGE=981
 - PAGE=982
 - PAGE=983
 - PAGE=984
 - PAGE=985
 - PAGE=986
 - PAGE=987
 - PAGE=988
 - PAGE=989
 - PAGE=990
 - PAGE=991
 - PAGE=992
 - PAGE=993
 - PAGE=994
 - PAGE=995
 - PAGE=996
 - PAGE=997
 - PAGE=998
 - PAGE=999
